<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>duration</name>
   <tag></tag>
   <elementGuidId>f0ed231e-d118-4118-907c-d0408d1dfbe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='RULE_KEY']/div/div/div/div[3]/div/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
