<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>starDate</name>
   <tag></tag>
   <elementGuidId>323ae8c4-ad8b-4a79-9ed6-ecde4aa30b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='RULE_KEY']/div/div/div/div[1]/div/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
